import type {
  Alert,
  ArchonHunt,
  Baro,
  Cycle,
  Fissure,
  Invasion,
  Nightwave,
  Reward,
  Sortie,
  WorldState,
} from "../../lib/contracts/worldstate";
import { STALE_AFTER_MS } from "./normalize";
import tables from "./de-names.json";

// DE's own world state. Every value in it is an internal id, so this file is mostly translation.
// The lookup tables are generated by scripts/build-de-names.mjs from WFCD warframe-worldstate-data,
// shipped as JSON rather than fetched so the fallback never depends on a second upstream.
export const DE_ENDPOINT = "https://api.warframe.com/cdn/worldState.php";

type Raw = Record<string, unknown>;

interface NameTables {
  nodes: Record<string, { value: string; enemy: string; type: string }>;
  missionTypes: Record<string, string>;
  factions: Record<string, string>;
  sortieBosses: Record<string, { name: string; faction: string }>;
  sortieModifiers: Record<string, string>;
  names: Record<string, string | { value: string; desc?: string }>;
}

const T = tables as NameTables;

const TIERS: Record<string, Fissure["tier"]> = {
  VoidT1: "Lith",
  VoidT2: "Meso",
  VoidT3: "Neo",
  VoidT4: "Axi",
  VoidT5: "Requiem",
  VoidT6: "Omnia",
};

function rec(value: unknown): Raw {
  return value !== null && typeof value === "object" ? (value as Raw) : {};
}

function arr(value: unknown): Raw[] {
  return Array.isArray(value) ? value.map(rec) : [];
}

function str(value: unknown): string {
  return value === undefined || value === null ? "" : String(value);
}

function num(value: unknown, fallback = 0): number {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : fallback;
}

// DE writes every date as a Mongo export, { "$date": { "$numberLong": "1788019200000" } }.
function ms(value: unknown): number {
  const inner = rec(rec(value).$date);
  return num(inner.$numberLong ?? rec(value).$date ?? value);
}

function node(key: unknown): string {
  const id = str(key);
  return T.nodes[id]?.value ?? id;
}

function nodeEnemy(key: unknown): string {
  return T.nodes[str(key)]?.enemy ?? "";
}

function nodeMissionType(key: unknown): string {
  return T.nodes[str(key)]?.type ?? "";
}

function missionType(key: unknown): string {
  const id = str(key);
  return T.missionTypes[id] ?? id;
}

function faction(key: unknown): string {
  const id = str(key);
  return T.factions[id] ?? id;
}

// Item, challenge and headline paths all resolve through the same language table.
function named(path: unknown): { value: string; desc: string } {
  const entry = T.names[str(path).toLowerCase()];
  if (typeof entry === "string") return { value: entry, desc: "" };
  if (entry) return { value: entry.value, desc: entry.desc ?? "" };
  // Unknown path, the tail of it still reads better than the whole /Lotus string.
  return { value: str(path).split("/").pop() ?? "", desc: "" };
}

function rewards(value: unknown): Reward[] {
  const raw = rec(value);
  const out: Reward[] = [];
  for (const item of Array.isArray(raw.items) ? raw.items : []) {
    out.push({ item: named(item).value, count: 1, credits: 0 });
  }
  for (const counted of arr(raw.countedItems)) {
    out.push({ item: named(counted.ItemType).value, count: num(counted.ItemCount, 1), credits: 0 });
  }
  if (num(raw.credits) > 0) out.push({ item: "Credits", count: 1, credits: num(raw.credits) });
  return out;
}

function firstReward(value: unknown): Reward | null {
  return rewards(value)[0] ?? null;
}

// ActiveMissions are the plain fissures, VoidStorms are the Railjack ones. Storms carry no
// mission type of their own, the star chart node says what the Railjack mission is.
function fissures(raw: Raw): Fissure[] {
  const plain = arr(raw.ActiveMissions).map((m) => ({
    key: str(rec(m._id).$oid),
    node: node(m.Node),
    missionType: missionType(m.MissionType),
    enemy: nodeEnemy(m.Node),
    tier: TIERS[str(m.Modifier)] ?? "Lith",
    steelPath: Boolean(m.Hard),
    storm: false,
    startsAt: ms(m.Activation),
    expiresAt: ms(m.Expiry),
  }));
  const storms = arr(raw.VoidStorms).map((s) => ({
    key: str(rec(s._id).$oid),
    node: node(s.Node),
    missionType: nodeMissionType(s.Node),
    enemy: nodeEnemy(s.Node),
    tier: TIERS[str(s.ActiveMissionTier)] ?? "Lith",
    steelPath: false,
    storm: true,
    startsAt: ms(s.Activation),
    expiresAt: ms(s.Expiry),
  }));
  return [...plain, ...storms];
}

function alerts(raw: Raw): Alert[] {
  return arr(raw.Alerts).map((a) => {
    const info = rec(a.MissionInfo);
    return {
      key: str(rec(a._id).$oid),
      node: node(info.location),
      missionType: missionType(info.missionType),
      enemy: faction(info.faction),
      rewards: rewards(info.missionReward),
      startsAt: ms(a.Activation),
      expiresAt: ms(a.Expiry),
    };
  });
}

// Count runs from minus Goal (attacker winning) to plus Goal, panels want a defender percentage.
function invasions(raw: Raw): Invasion[] {
  return arr(raw.Invasions)
    .filter((i) => !i.Completed)
    .map((i) => ({
      key: str(rec(i._id).$oid),
      node: node(i.Node),
      description: named(i.LocTag).value,
      attacker: { faction: faction(i.Faction), reward: firstReward(i.AttackerReward) },
      defender: { faction: faction(i.DefenderFaction), reward: firstReward(i.DefenderReward) },
      completion: ((1 + num(i.Count) / num(i.Goal, 1)) / 2) * 100,
      startsAt: ms(i.Activation),
    }));
}

function sortie(raw: Raw): Sortie | null {
  const s = arr(raw.Sorties)[0];
  if (!s) return null;
  const boss = T.sortieBosses[str(s.Boss)];
  return {
    key: str(rec(s._id).$oid),
    boss: boss?.name ?? str(s.Boss),
    faction: boss?.faction ?? "",
    missions: arr(s.Variants).map((v) => ({
      node: node(v.node),
      missionType: missionType(v.missionType),
      modifier: T.sortieModifiers[str(v.modifierType)] ?? str(v.modifierType),
    })),
    startsAt: ms(s.Activation),
    expiresAt: ms(s.Expiry),
  };
}

// LiteSorties is the archon hunt. It lists Missions, not Variants, and carries no modifiers.
function archonHunt(raw: Raw): ArchonHunt | null {
  const a = arr(raw.LiteSorties)[0];
  if (!a) return null;
  const boss = T.sortieBosses[str(a.Boss)];
  return {
    key: str(rec(a._id).$oid),
    boss: boss?.name ?? str(a.Boss),
    faction: boss?.faction ?? "",
    missions: arr(a.Missions).map((m) => ({
      node: node(m.node),
      missionType: missionType(m.missionType),
      modifier: "",
    })),
    startsAt: ms(a.Activation),
    expiresAt: ms(a.Expiry),
  };
}

function baro(raw: Raw, at: number): Baro | null {
  const b = arr(raw.VoidTraders)[0];
  if (!b) return null;
  const startsAt = ms(b.Activation);
  return {
    key: str(rec(b._id).$oid) + ":" + startsAt,
    location: node(b.Node),
    active: startsAt <= at && at < ms(b.Expiry),
    startsAt,
    expiresAt: ms(b.Expiry),
    inventory: arr(b.Manifest).map((i) => ({
      item: named(i.ItemType).value,
      ducats: num(i.PrimePrice),
      credits: num(i.RegularPrice),
    })),
  };
}

// DE ships the challenge path, not the standing. Standing is fixed per tier: daily, weekly, elite.
function reputation(challenge: string, daily: boolean): number {
  if (daily) return 1000;
  return /weeklyhard/i.test(challenge) ? 7000 : 4500;
}

function nightwave(raw: Raw): Nightwave | null {
  const n = rec(raw.SeasonInfo);
  if (n.Season === undefined) return null;
  return {
    season: num(n.Season),
    expiresAt: ms(n.Expiry),
    acts: arr(n.ActiveChallenges).map((c) => {
      const challenge = str(c.Challenge);
      const { value, desc } = named(challenge);
      return {
        key: str(rec(c._id).$oid),
        title: value,
        description: desc,
        reputation: reputation(challenge, Boolean(c.Daily)),
        daily: Boolean(c.Daily),
        expiresAt: ms(c.Expiry),
      };
    }),
  };
}

function syndicateExpiry(raw: Raw, tag: string): number {
  const found = arr(raw.SyndicateMissions).find((s) => str(s.Tag) === tag);
  return found ? ms(found.Expiry) : 0;
}

// Cetus runs 100 minutes of day then 50 of night, and the Ostron bounty rotation ends with night.
function cetus(bountyEnd: number, at: number): { state: string; expiresAt: number } | null {
  if (!bountyEnd) return null;
  const nightEnd = Math.floor(bountyEnd / 60_000) * 60_000;
  const secondsToNightEnd = Math.round((nightEnd - at) / 1000);
  const day = secondsToNightEnd > 3000;
  const left = (day ? secondsToNightEnd - 3000 : secondsToNightEnd) * 1000;
  return { state: day ? "day" : "night", expiresAt: Math.round((at + left) / 60_000) * 60_000 };
}

// Earth is a plain 8 hour cycle aligned to the unix epoch, 4 hours of day then 4 of night.
function earth(at: number): { state: string; expiresAt: number } {
  const inCycle = Math.floor(at / 1000) % 28800;
  const day = inCycle < 14400;
  return { state: day ? "day" : "night", expiresAt: at + (14400 - (inCycle % 14400)) * 1000 };
}

// Vallis loops every 26m40s, warm for the first 6m40s, from a known warm start.
const VALLIS_START = Date.parse("2026-02-04T19:46:48Z");

function vallis(at: number): { state: string; expiresAt: number } {
  const toNextFull = 1_600_000 - ((at - VALLIS_START) % 1_600_000);
  const warm = toNextFull > 1_200_000;
  const left = warm ? toNextFull - 1_200_000 : toNextFull;
  return { state: warm ? "warm" : "cold", expiresAt: at + left };
}

// Duviri walks five two hour spirals, the sequence is anchored 52 seconds after the epoch.
const SPIRALS = ["sorrow", "fear", "joy", "anger", "envy"];

function duviri(at: number): { state: string; expiresAt: number } {
  const inCycle = (Math.floor(at / 1000) - 52) % 36000;
  const left = 7200 - (inCycle % 7200);
  const expiry = new Date(at + left * 1000);
  expiry.setSeconds(0, 0);
  return { state: SPIRALS[Math.floor(inCycle / 7200)], expiresAt: expiry.getTime() };
}

// Zariman flips faction every 2.5 hours, on the Holdfasts bounty clock, from a confirmed Corpus start.
const ZARIMAN_CORPUS_START = 1_655_182_800_000;

function zariman(bountyEnd: number): { state: string; expiresAt: number } | null {
  if (!bountyEnd) return null;
  const anchor = bountyEnd - 5000;
  const elapsed = (((anchor - ZARIMAN_CORPUS_START) % 18_000_000) + 18_000_000) % 18_000_000;
  const corpus = 18_000_000 - elapsed > 9_000_000;
  return {
    state: corpus ? "corpus" : "grineer",
    expiresAt: Math.round(anchor / 60_000) * 60_000,
  };
}

// DE does not ship the open world cycles, they are computed. A cycle we cannot derive is left out.
function cycles(raw: Raw, at: number): Cycle[] {
  const cetusCycle = cetus(syndicateExpiry(raw, "CetusSyndicate"), at);
  const out: Cycle[] = [];
  const push = (world: Cycle["world"], c: { state: string; expiresAt: number } | null) => {
    if (c) out.push({ world, state: c.state, expiresAt: c.expiresAt });
  };
  push("cetus", cetusCycle);
  push("vallis", vallis(at));
  // Cambion rides the Cetus clock, fass is day and vome is night.
  push("cambion", cetusCycle && { state: cetusCycle.state === "day" ? "fass" : "vome", expiresAt: cetusCycle.expiresAt });
  push("earth", earth(at));
  push("duviri", duviri(at));
  push("zariman", zariman(syndicateExpiry(raw, "ZarimanSyndicate")));
  return out;
}

export function normalizeDe(raw: Raw, fetchedAt: number = Date.now()): WorldState {
  const upstreamTimestamp = num(raw.Time) * 1000 || fetchedAt;
  return {
    platform: "pc",
    fetchedAt,
    source: "de",
    upstreamTimestamp,
    stale: fetchedAt - upstreamTimestamp > STALE_AFTER_MS,
    fissures: fissures(raw),
    alerts: alerts(raw),
    invasions: invasions(raw),
    sortie: sortie(raw),
    archonHunt: archonHunt(raw),
    baro: baro(raw, fetchedAt),
    nightwave: nightwave(raw),
    cycles: cycles(raw, fetchedAt),
  };
}
