import { v } from "convex/values";
import { internalQuery } from "../_generated/server";
import { NAME_TABLES } from "./nameTables";

// Star chart node lookups, shared by the DE parser and the schedule files, which both speak
// in SolNode ids. The table is generated by scripts/build-de-names.mjs.
const NODES = NAME_TABLES.nodes;

// An id we cannot translate still reads better as the id than as an empty row.
export function nodeName(key: unknown): string {
  const id = String(key ?? "");
  return NODES[id]?.value ?? id;
}

export function nodeEnemy(key: unknown): string {
  return NODES[String(key ?? "")]?.enemy ?? "";
}

export function nodeMissionType(key: unknown): string {
  return NODES[String(key ?? "")]?.type ?? "";
}

// The /Lotus item paths are 550 KB, far too much to ship in every function bundle, and a snapshot
// only ever names a few hundred of them. They live in the deNames table, seeded by
// scripts/seed-tables.mjs, and ingest reads the ones its snapshot mentions before it parses.
export const lookup = internalQuery({
  args: { paths: v.array(v.string()) },
  returns: v.array(v.object({ path: v.string(), value: v.string(), desc: v.string() })),
  handler: async (ctx, { paths }) => {
    const found = [];
    for (const path of [...new Set(paths)]) {
      const row = await ctx.db
        .query("deNames")
        .withIndex("by_path", (q) => q.eq("path", path))
        .unique();
      if (row) found.push({ path: row.path, value: row.value, desc: row.desc ?? "" });
    }
    return found;
  },
});
