import raw from "./de-names.json";

// The one place the shipped name tables are typed. Casting here, once, is what keeps tsc from
// inferring a literal type for every key in the file. Generated by scripts/build-de-names.mjs.
export interface NodeEntry {
  value: string;
  enemy: string;
  type: string;
}

export type NameEntry = string | { value: string; desc?: string };

export interface NameTables {
  nodes: Record<string, NodeEntry>;
  missionTypes: Record<string, string>;
  factions: Record<string, string>;
  sortieBosses: Record<string, { name: string; faction: string }>;
  sortieModifiers: Record<string, string>;
  syndicates: Record<string, string>;
  bountyRewards: Record<string, string[]>;
  // Bare ids only. The /Lotus paths are 550 KB, they live in the deNames table.
  modifiers: Record<string, NameEntry>;
}

export const NAME_TABLES = raw as NameTables;
