import tables from "./de-names.json";

// Star chart node lookups, shared by the DE parser and the schedule files, which both speak
// in SolNode ids. The table is generated by scripts/build-de-names.mjs.
interface NodeEntry {
  value: string;
  enemy: string;
  type: string;
}

const NODES = (tables as { nodes: Record<string, NodeEntry> }).nodes;

// An id we cannot translate still reads better as the id than as an empty row.
export function nodeName(key: unknown): string {
  const id = String(key ?? "");
  return NODES[id]?.value ?? id;
}

export function nodeEnemy(key: unknown): string {
  return NODES[String(key ?? "")]?.enemy ?? "";
}

export function nodeMissionType(key: unknown): string {
  return NODES[String(key ?? "")]?.type ?? "";
}
