import arbitrationsRaw from "./arbitrations.json";
import incursionsRaw from "./spIncursions.json";
import tiersRaw from "./arbyTiers.json";

// Same idea as nameTables: the schedules are cast once here, so tsc sees three small shapes
// instead of 800 literal day tuples. Regenerated by scripts/refresh-schedules.mjs.
export interface IncursionSchedule {
  source: string;
  from: number;
  days: string[][];
}

export interface ArbitrationSchedule {
  source: string;
  from: number;
  hours: string[];
}

export const INCURSIONS = incursionsRaw as IncursionSchedule;
export const ARBITRATIONS = arbitrationsRaw as ArbitrationSchedule;
export const ARBY_TIERS = (tiersRaw as { tiers: Record<string, string> }).tiers;
